/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author canta
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpImagen = new javax.swing.JPanel();
        jpPrincipal = new javax.swing.JPanel();
        jbRegistrar = new javax.swing.JButton();
        jbConsultar = new javax.swing.JButton();
        jbInformes = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jpIzquierda = new javax.swing.JPanel();
        jpDerecha = new javax.swing.JPanel();
        jpArriba = new javax.swing.JPanel();
        jpAbajo = new javax.swing.JPanel();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartOccupation - Inicio");
        setLocation(new java.awt.Point(400, 300));
        setPreferredSize(new java.awt.Dimension(1280, 790));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 835));

        jpImagen.setBackground(new java.awt.Color(0, 0, 0));
        jpImagen.setMaximumSize(new java.awt.Dimension(3840, 2160));
        jpImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Color de fondo transparente
        jpPrincipal.setBackground(new java.awt.Color(0, 0, 0, 0));
        jpPrincipal.setFont(new java.awt.Font("Arial", 1, 24));
        jpPrincipal.setOpaque(false);
        jpPrincipal.setPreferredSize(new java.awt.Dimension(400, 300));
        jpPrincipal.setLayout(new java.awt.GridLayout(4, 1, 10, 10));

        jbRegistrar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbRegistrar.setText("Registrar Nuevo Alquiler");
        jbRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbRegistrar);

        jbConsultar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbConsultar.setText("Consultar Alquileres");
        jbConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbConsultar);

        jbInformes.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbInformes.setText("Generar Informes");
        jbInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInformesActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbInformes);

        jbSalir.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jpPrincipal.add(jbSalir);

        jpImagen.add(jpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 482, 361));

        jpIzquierda.setOpaque(false);
        jpIzquierda.setPreferredSize(new java.awt.Dimension(400, 357));

        javax.swing.GroupLayout jpIzquierdaLayout = new javax.swing.GroupLayout(jpIzquierda);
        jpIzquierda.setLayout(jpIzquierdaLayout);
        jpIzquierdaLayout.setHorizontalGroup(
            jpIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jpIzquierdaLayout.setVerticalGroup(
            jpIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jpImagen.add(jpIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 475));

        jpDerecha.setOpaque(false);
        jpDerecha.setPreferredSize(new java.awt.Dimension(400, 343));

        javax.swing.GroupLayout jpDerechaLayout = new javax.swing.GroupLayout(jpDerecha);
        jpDerecha.setLayout(jpDerechaLayout);
        jpDerechaLayout.setHorizontalGroup(
            jpDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jpDerechaLayout.setVerticalGroup(
            jpDerechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jpImagen.add(jpDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(923, 180, 350, 475));

        jpArriba.setOpaque(false);
        jpArriba.setPreferredSize(new java.awt.Dimension(1093, 180));

        javax.swing.GroupLayout jpArribaLayout = new javax.swing.GroupLayout(jpArriba);
        jpArriba.setLayout(jpArribaLayout);
        jpArribaLayout.setHorizontalGroup(
            jpArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jpArribaLayout.setVerticalGroup(
            jpArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpImagen.add(jpArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        jpAbajo.setOpaque(false);
        jpAbajo.setPreferredSize(new java.awt.Dimension(1093, 200));

        javax.swing.GroupLayout jpAbajoLayout = new javax.swing.GroupLayout(jpAbajo);
        jpAbajo.setLayout(jpAbajoLayout);
        jpAbajoLayout.setHorizontalGroup(
            jpAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jpAbajoLayout.setVerticalGroup(
            jpAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jpImagen.add(jpAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 655, 1280, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/house-2368389_1280.jpg"))); // NOI18N
        jlFondo.setMaximumSize(new java.awt.Dimension(1290, 835));
        jlFondo.setMinimumSize(new java.awt.Dimension(1290, 835));
        jlFondo.setPreferredSize(new java.awt.Dimension(1290, 835));
        jpImagen.add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 1277, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarActionPerformed
        // Abre la ventana con el formulario de registro
        new VentanaRegistroAlquiler().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbRegistrarActionPerformed

    private void jbConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarActionPerformed
        // Abre la ventana de consultas.
        new VentanaConsultarAlquileres().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbConsultarActionPerformed

    private void jbInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInformesActionPerformed
        // Abre la ventana de generación de informes
        new VentanaGenerarInforme().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbInformesActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // Cierra el programa
        System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbInformes;
    private javax.swing.JButton jbRegistrar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JPanel jpAbajo;
    private javax.swing.JPanel jpArriba;
    private javax.swing.JPanel jpDerecha;
    private javax.swing.JPanel jpImagen;
    private javax.swing.JPanel jpIzquierda;
    private javax.swing.JPanel jpPrincipal;
    // End of variables declaration//GEN-END:variables
}
